language: python

cache:
  - pip
  - directories:
    - $HOME/Library/Caches/pip
    - $HOME/Download

matrix:
  include:
    - name: "Python 3.6 (OS X)"
      os: osx
      osx_image: xcode8
      language: generic
      env:
        PYTHON: python3.6
        PYTHON_INSTALLER_URL: https://www.python.org/ftp/python/3.6.8/python-3.6.8-macosx10.6.pkg
        PYTHON_INSTALLER_MD5: eb1a23d762946329c2aa3448d256d421
        PATH: /Users/travis/Library/Python/3.6/bin:$PATH
    - name: "Python 3.7 (OS X)"
      os: osx
      osx_image: xcode8
      language: generic
      env:
        PYTHON: python3.7
        PYTHON_INSTALLER_URL: https://www.python.org/ftp/python/3.7.9/python-3.7.9-macosx10.9.pkg
        PYTHON_INSTALLER_MD5: 4b544fc0ac8c3cffdb67dede23ddb79e
        PATH: /Users/travis/Library/Python/3.7/bin:$PATH
    - name: "Python 3.8 (OS X)"
      os: osx
      osx_image: xcode8
      language: generic
      env:
        PYTHON: python3.8
        PYTHON_INSTALLER_URL: https://www.python.org/ftp/python/3.8.6/python-3.8.6-macosx10.9.pkg
        PYTHON_INSTALLER_MD5: 68170127a953e7f12465c1798f0965b8
        PATH: /Users/travis/Library/Python/3.8/bin:$PATH
    - name: "Python 3.9 (OS X)"
      os: osx
      osx_image: xcode8
      language: generic
      env:
        PYTHON: python3.9
        PYTHON_INSTALLER_URL: https://www.python.org/ftp/python/3.9.0/python-3.9.0-macosx10.9.pkg
        PYTHON_INSTALLER_MD5: 16ca86fa3467e75bade26b8a9703c27f
        PATH: /Users/travis/Library/Python/3.9/bin:$PATH
    - name: "Python 3.6 (Linux)"
      os: linux
      dist: bionic
      python: "3.6"
    - name: "Python 3.7 (Linux)"
      os: linux
      dist: bionic
      python: "3.7"
    - name: "Python 3.8 (Linux)"
      os: linux
      dist: bionic
      python: "3.8"
    - name: "Python 3.9 (Linux)"
      os: linux
      dist: bionic
      python: "3.9"

git:
  depth: 1

install:
  - ./ci/travis-install.sh

script:
  - export SOURCE_DATE_EPOCH="$(git log -1 --date=unix --format='format:%ct' rtmidi/version.py)"
  - ${PYTHON:-python} setup.py release

deploy:
  provider: script
  skip_cleanup: true
  script:
    - ./ci/travis-deploy.sh
  on:
    all_branches: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
